# Generated by Django 3.2.12 on 2022-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='Stream',
        ),
        migrations.AlterField(
            model_name='details',
            name='Address',
            field=models.CharField(choices=[('Arumbakkam', 'Arumbakkam'), ('', '')], max_length=255),
        ),
        migrations.AlterField(
            model_name='details',
            name='BloodGroup',
            field=models.CharField(choices=[('B+', 'B+'), ('A+', 'A+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A1B+', 'A1B+'), ('B-', 'B-'), ('A-', 'A-'), ('O-', 'O-'), ('AB-', 'AB-'), ('A1B-', 'A1B-')], max_length=7),
        ),
        migrations.AlterField(
            model_name='details',
            name='Branch',
            field=models.CharField(choices=[('MSc_Integrated', 'MSc_Integrated'), ('BE_Civil', 'BE_Civil'), ('BE_Mechanical', 'BE_Mechanical'), ('BE_Biotech', 'Biotech'), ('BE_EEE', 'BE_EEE'), ('BE_ECE', 'BE_ECE'), ('BE_CS', 'BE_CS'), ('BE_IT', 'BE_IT'), ('BE_Industrial', 'BE_Industrial'), ('BE_Manufacturing', 'BE_Manufacturing'), ('BE_Material_Science', 'BE_Material_Science')], max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Campus',
            field=models.CharField(choices=[('CEG', 'CEG'), ('ACT', 'ACT'), ('SAP', 'SAP')], max_length=3),
        ),
    ]
