# Generated by Django 3.2.12 on 2022-03-22 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220321_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablevolunteer',
            name='PickupArea',
            field=models.CharField(choices=[('Arumbakkam', 'Arumbakkam'), ('Kattupakkam', 'Kattupakkam'), ('Guindy', 'Guindy'), ('Ramapuram', 'Ramapuram'), ('Porur', 'Porur'), ('Poonamallee', 'Poonamallee'), ('AnnaNagar', 'AnnaNagar'), ('TNagar', 'TNagar'), ('CMBT', 'CMBT'), ('Adyar', 'Adyar'), ('Alwarpet', 'Alwarpet'), ('Kodambakkam', 'Kodambakkam'), ('Valasaravakkam', 'Valasaravakkam'), ('Nungambakkam', 'Nungambakkam'), ('Mogappair', 'Mogappair'), ('Royapuram', 'Royapuram'), ('Nandanam', 'Nandanam'), ('Saidapet', 'Saidapet'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='Address',
            field=models.CharField(choices=[('Arumbakkam', 'Arumbakkam'), ('Kattupakkam', 'Kattupakkam'), ('Guindy', 'Guindy'), ('Ramapuram', 'Ramapuram'), ('Porur', 'Porur'), ('Poonamallee', 'Poonamallee'), ('AnnaNagar', 'AnnaNagar'), ('TNagar', 'TNagar'), ('CMBT', 'CMBT'), ('Adyar', 'Adyar'), ('Alwarpet', 'Alwarpet'), ('Kodambakkam', 'Kodambakkam'), ('Valasaravakkam', 'Valasaravakkam'), ('Nungambakkam', 'Nungambakkam'), ('Mogappair', 'Mogappair'), ('Royapuram', 'Royapuram'), ('Nandanam', 'Nandanam'), ('Saidapet', 'Saidapet'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='HomeArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentarea'),
        ),
        migrations.AlterField(
            model_name='studentarea',
            name='Area',
            field=models.CharField(choices=[('Arumbakkam', 'Arumbakkam'), ('Kattupakkam', 'Kattupakkam'), ('Guindy', 'Guindy'), ('Ramapuram', 'Ramapuram'), ('Porur', 'Porur'), ('Poonamallee', 'Poonamallee'), ('AnnaNagar', 'AnnaNagar'), ('TNagar', 'TNagar'), ('CMBT', 'CMBT'), ('Adyar', 'Adyar'), ('Alwarpet', 'Alwarpet'), ('Kodambakkam', 'Kodambakkam'), ('Valasaravakkam', 'Valasaravakkam'), ('Nungambakkam', 'Nungambakkam'), ('Mogappair', 'Mogappair'), ('Royapuram', 'Royapuram'), ('Nandanam', 'Nandanam'), ('Saidapet', 'Saidapet'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteerarea',
            name='Area',
            field=models.CharField(choices=[('Arumbakkam', 'Arumbakkam'), ('Kattupakkam', 'Kattupakkam'), ('Guindy', 'Guindy'), ('Ramapuram', 'Ramapuram'), ('Porur', 'Porur'), ('Poonamallee', 'Poonamallee'), ('AnnaNagar', 'AnnaNagar'), ('TNagar', 'TNagar'), ('CMBT', 'CMBT'), ('Adyar', 'Adyar'), ('Alwarpet', 'Alwarpet'), ('Kodambakkam', 'Kodambakkam'), ('Valasaravakkam', 'Valasaravakkam'), ('Nungambakkam', 'Nungambakkam'), ('Mogappair', 'Mogappair'), ('Royapuram', 'Royapuram'), ('Nandanam', 'Nandanam'), ('Saidapet', 'Saidapet'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=50),
        ),
    ]
