# Generated by Django 3.2.12 on 2022-03-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220322_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='Status',
            field=models.BooleanField(),
        ),
    ]
