# Generated by Django 3.2.12 on 2022-04-27 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='Volunteer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
