# Generated by Django 3.2.12 on 2022-04-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220427_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrequest',
            old_name='StudentRequest',
            new_name='StudentArea',
        ),
    ]
