# Generated by Django 3.2.12 on 2022-04-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_student_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student',
            new_name='User',
        ),
    ]
