# Generated by Django 3.2.12 on 2022-04-27 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_rename_student_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='User',
            new_name='User1',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='User1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
